<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class UserRegistrationRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'name' => 'required|min:3|max:8',
            'lastName' => 'required|min:3|max:12',
            'email' => 'required|email:rfc,dns|unique:users,email',
            'password' => 'required|min:6',
            'passwordConfirm' => 'required|same:password',
            'profileImage' => 'required',
        ];
    }

//    protected function failedValidation(Validator $validator)
//    {
//        dd($validator->errors(), $this->all());
//        parent::failedValidation($validator); // TODO: Change the autogenerated stub
//    }
}
